const ActionType = {
    ADD_TASK: 'TODOLIST/ADD_TASK',
    DELETE_TASK: 'TODOLIST/DELETE_TASK',
    SET_MESSAGE_ERROR: 'TODOLIST/SET_MESSAGE_ERROR',
    CHANGE_STATUS_TASK: 'TODOLIST/CHANGE_STATUS_TASK',
    CHANGE_TASK: 'TODOLIST/CHANGE_TASK',
    SET_TASK: 'TODOLIST/SET_TASK',
    CHANGE_FILTER: 'TODOLIST/CHANGE_FILTER'
};

export default ActionType;